name: Python package

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Library install
      run: |
        pip install requests
        pip install pandas
        pip install beautifulsoup4
        pip install lxml
        pip install selenium
        pip install webdriver_manager
       
    - name: Create city folders
      run: |
        mkdir -p seoul
        mkdir -p Busan
        mkdir -p Daegu

    - name: Run script to collect data
      run: |
        python3 travelrank.py

    - name: Move generated files to respective folders
      run: |
        for file in chart_travel-*.json; do
          city=$(echo "$file" | cut -d'-' -f3)
          mkdir -p "$city"
          mv "$file" "$city/"
        done

    - name: Commit changes
      run: |
        git config --global user.email "rhthrck12@gmail.com"
        git config --global user.name "123dd654"
        git add seoul/ Busan/ Daegu/
        git commit -m "Update travel data"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with: 
        branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
